### ISSUE TITLE
Upgrade to Analytics v4.7.1 broke Nextcloud-AIO v25.0.3

### ISSUE THREAD

**Issue by Bruceumba** [Rello/analytics#333]
I updated to Analytics v4.7.1 today, and it put Nextcloud into maintenance mode. I needed to disable the app using an occ command to get my Nextcloud install working again. I reported this on the Nextcloud-AIO git discussion, as I suspect that's where the fix needs to happen: https://github.com/nextcloud/all-in-one/discussions/1975
Bruce

**Comment by Rello** [comment]
Hi,
no issues on my (non AIO) instances. any log?

**Comment by MartinDerHettich** [comment]
Same here, approx 5 minutes after upgrade of Analytics, from version 4.6 to 4.7.1:

```
ParseError: syntax error, unexpected '|', expecting ';' or '{' in /var/www/html/nextcloud/apps/analytics/lib/Datasource/Github.php:119
Stack trace:
#0 /var/www/html/nextcloud/lib/composer/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 [internal function]: spl_autoload_call()
#3 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): ReflectionClass->__construct()
#4 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#10 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#13 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#14 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#16 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#17 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#18 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#19 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(437): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#21 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(89): OC\AppFramework\DependencyInjection\DIContainer->query()
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#23 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): array_map()
#24 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(116): OC\AppFramework\Utility\SimpleContainer->buildClass()
#25 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(133): OC\AppFramework\Utility\SimpleContainer->resolve()
#26 /var/www/html/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(465): OC\AppFramework\Utility\SimpleContainer->query()
#27 /var/www/html/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#28 /var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php(303): OC\ServerContainer->query()
#29 /var/www/html/nextcloud/lib/private/BackgroundJob/JobList.php(241): OC\BackgroundJob\JobList->buildJob()
#30 /var/www/html/nextcloud/cron.php(144): OC\BackgroundJob\JobList->getNext()
#31 {main}
```

**Comment by Rello** [comment]
Hello,
return types should not be the problem. which PHP version are you using?

**Comment by MartinDerHettich** [comment]
PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

**Comment by Rello** [comment]
ah. ok.
my mistake that I did not adjust the min-php version in info.xml. I will push a corrected version

**Comment by Rello** [comment]
problem is caused by mixed return types in 2 places, which were introduced in PHP8
https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.mixed

**Comment by MartinDerHettich** [comment]
Thanks

**Comment by Rello** [comment]
v4.7.2 was released
